version: '3.7'

services:

  db:
    image: mongo:3.6.7-jessie
    container_name: db
    ports:
      - 27018:27017
    volumes:
      - ./data_mongo:/data/db
    restart: on-failure

  api:
    build:
      context: ./backend
    container_name: api
    ports: 
      - 5000:8080
    links: 
      - db
    depends_on:
      - db
    restart: on-failure